Add -fgnu89-inline to CFLAGS
In GCC 5.1 default C standard changed to -std=gnu11. This changed behavior of
inline functions. Build error is:
[  184s] CMakeFiles/menu-screen.dir/src/page_scroller.c.o: In function `page_scroller_bring_in':
[  184s] /home/abuild/rpmbuild/BUILD/org.tizen.menu-screen-1.1.1/src/page_scroller.c:74: undefined reference to `index_bring_in'
[  184s] collect2: error: ld returned 1 exit status

Changing back to gnu89 inlining mode fixes the issue.

Change-Id: If7b6b199f14ab4652e5c9de562e554942be1eb17
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>